services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: bash ./start.sh
    env_file:
      - $REMOTE_PROJECT_DIR/..env
    volumes:
      - ./:/app
      - ./:/app/logs

volumes:
    backend:
