FROM python:3.12.3

RUN apt-get update && apt-get install -y \
    nano && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY src /app/src
COPY queue_start.sh /app/queue_start.sh
COPY ./poetry.lock .
COPY ./pyproject.toml .

RUN pip install poetry --break-system-packages && \
    poetry config virtualenvs.create false && \
    poetry install --no-interaction --no-ansi

RUN chmod +x /app/queue_start.sh
