"""update call session model

Revision ID: 90874da30758
Revises: c0a01fdc1ee0
Create Date: 2025-09-22 21:43:36.542307

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "90874da30758"
down_revision: Union[str, None] = "c0a01fdc1ee0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("call_sessions", sa.Column("text_from_audio", sa.Text(), nullable=True))
    op.alter_column("call_sessions", "script", existing_type=postgresql.JSON(astext_type=sa.Text()), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("call_sessions", "script", existing_type=postgresql.JSON(astext_type=sa.Text()), nullable=False)
    op.drop_column("call_sessions", "text_from_audio")
    # ### end Alembic commands ###
