"""Описаниеupdate call session model

Revision ID: bc8e0243d765
Revises: 5aaab933dd70
Create Date: 2025-09-29 21:55:31.573979

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = "bc8e0243d765"
down_revision: Union[str, None] = "5aaab933dd70"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="callsessionstatus",
        new_values=[
            "Received",
            "In processing",
            "Receiving transcription",
            "Error receiving transcription",
            "Receiving analytics",
            "Error receiving analytics",
            "Processing completed",
            "Fake dialogue",
        ],
        affected_columns=[
            TableReference(table_schema="public", table_name="call_sessions", column_name="type_campaign")
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="callsessionstatus",
        new_values=[
            "Received",
            "In processing",
            "Receiving transcription",
            "Error receiving transcription",
            "Receiving analytics",
            "Error receiving analytics",
            "Processing completed",
        ],
        affected_columns=[
            TableReference(table_schema="public", table_name="call_sessions", column_name="type_campaign")
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
