"""update processing log model

Revision ID: 5aaab933dd70
Revises: 376998e87f8e
Create Date: 2025-09-28 00:40:24.600253

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5aaab933dd70"
down_revision: Union[str, None] = "376998e87f8e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("processing_logs", "request", existing_type=sa.TEXT(), nullable=True)
    op.alter_column("processing_logs", "response", existing_type=sa.TEXT(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("processing_logs", "response", existing_type=sa.TEXT(), nullable=False)
    op.alter_column("processing_logs", "request", existing_type=sa.TEXT(), nullable=False)
    # ### end Alembic commands ###
